[project]
name = "new-pmedia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "diskcache>=5.6.3",
    "dotenv>=0.9.9",
    "elevenlabs>=2.27.0",
    "openai>=2.14.0",
    "rich>=13.7.0",
    "typer>=0.20.1",
]
